export const stlFiles = [
  // Base components
  'base-front-bottom.stl',
  'base-left-bottom.stl',
  'base-left-top.stl',
  'base-right-bottom.stl',
  'base-right-top.stl',

  // Black components
  'black-6x30-finderscope-mount.stl',
  'black-Baffle.stl',
  'black-Celestron-51630-Red-Dot.stl',
  'black-Dovetail-mount.stl',
  'black-Mirror-Cell---Primary.stl',
  'black-Mirror-Cell---Secondary.stl',
  'black-NRF---Collet.stl',
  'black-NRF---Drawtube.stl',
  'black-Spider-curved-single-nut.stl',
  'black-Svbony-SV182-6x30-finderscope.stl',
  'black-UTA-Sleeve.stl',

  // Gray components
  'gray-Hex-bolt-M4x0.7-x-50mm_1.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm_2.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm_3.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm_4.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm_5.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm_6.stl',
  'gray-Hex-bolt-M4x0.7-x-50mm.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_10.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_11.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_12.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_13.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_14.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_15.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_16.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_17.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_18.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_19.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_1.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_20.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_21.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_22.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_23.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_24.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_25.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_26.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_27.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_28.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_29.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_2.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_30.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_31.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_32.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_33.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_34.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_35.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_36.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_37.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_38.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_3.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_4.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_5.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_6.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_7.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_8.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7_9.stl',
  'gray-Hex-nut-grade-A---B-M4x0.7.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_10.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_11.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_12.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_13.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_14.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_15.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_16.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_17.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_18.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_1.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_2.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_3.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_4.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_5.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_6.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_7.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_8.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12_9.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-12.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-16_1.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-16_2.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-16_3.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-16.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_1.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_2.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_3.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_4.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_5.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_6.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20_7.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-20.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-25_1.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-25.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-8_1.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-8_2.stl',
  'gray-Hex-socket-head-cap-screw-M4x0.70-x-8.stl',
  'gray-Nut-dome-M4x0.7_1.stl',
  'gray-Nut-dome-M4x0.7_2.stl',
  'gray-Nut-dome-M4x0.7.stl',
  'gray-Nut-nyloc-M4x0.7_1.stl',
  'gray-Nut-nyloc-M4x0.7_2.stl',
  'gray-Nut-nyloc-M4x0.7_3.stl',
  'gray-Nut-nyloc-M4x0.7.stl',

  // Mirror components
  'mirror-Mirror---Primary.stl',
  'mirror-Secondary-mirror.stl',

  // Mount/Structural components
  'mount-base.stl',

  // Rod components
  'rod-base-bottom-back.stl',
  'rod-base-bottom-front-top-front-left.stl',
  'rod-base-bottom-front-top-front-right.stl',
  'rod-base-bottom-left.stl',
  'rod-base-bottom-left-top-back-left.stl',
  'rod-base-bottom-left-top-front-left.stl',
  'rod-base-bottom-right.stl',
  'rod-base-bottom-right-top-back-right.stl',
  'rod-base-bottom-right-top-front-right.stl',
  'rod-base-top.stl',
  'rod-ota-1-12mm_rod_1m.stl',
  'rod-ota-2-12mm_rod_1m_1.stl',
  'rod-ota-3-12mm_rod_1m_2.stl',

  // Tube A components
  'tube-a-Bearing-1.stl',
  'tube-a-Bearing-2.stl',
  'tube-a-farsight.stl',
  'tube-a-lta-for-sleeve.stl',
  'tube-a-NRF---Collet-Nut-knurled.stl',
  'tube-a-NRF---Retaining-Ring.stl',
  'tube-a-Thumbscrew-Small---M4-Nyloc.stl',
  'tube-a-uta-for-sleeve.stl',

  // Tube B components
  'tube-b-Bearing-Mount-Interface.stl',
  'tube-b-nearsight.stl',
  'tube-b-NRF---Base.stl',
  'tube-b-NRF--Nut-knurled.stl',
  'tube-b-secondary-collimation-plate.stl',
  'tube-b-thumbscrew-large-m4-nyloc_1.stl',
  'tube-b-thumbscrew-large-m4-nyloc_2.stl',
  'tube-b-thumbscrew-large-m4-nyloc.stl',
  'tube-b-thumbscrew-small-m4-hex-nut_1.stl',
  'tube-b-thumbscrew-small-m4-hex-nut_2.stl',
  'tube-b-thumbscrew-small-m4-hex-nut.stl'

];
